apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: adm-service
  name: adm-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: adm-service
  template:
    metadata:
      labels:
        k8s-app: adm-service
    spec:
      containers:
      - image: wavefronthq/adm-service:0.9.0
        imagePullPolicy: IfNotPresent
        name: adm-service
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
