apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavefront-collector-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wavefront-collector-operator
  template:
    metadata:
      labels:
        name: wavefront-collector-operator
    spec:
      serviceAccountName: wavefront-collector-operator
      containers:
        - name: wavefront-collector-operator
          image: wavefronthq/wavefront-collector-operator:v0.0.4
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "wavefront-collector-operator"
